name: Tests continus

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Debug structure
        run: ls -R

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: .

      - name: Run tests and generate HTML report
        run: |
          npx jest --ci
        working-directory: ./CLITestwebsite
        env:
          CI: true

      - name: Upload HTML test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: CLITestwebsite/test-report.html
