name: PR Security Scan

on:
  pull_request:
    branches: [ master ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create scans directory
        run: mkdir -p scans

      - name: Run security scan on example.com
        run: python main.py --domain example.com --formats json,html --scans-dir scans

      - name: Upload reports as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr-security-reports-${{ github.run_id }}
          path: scans/
          retention-days: 7