name: Code Quality Check

on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8

    - name: Check formatting with Black
      run: |
        black --check .

    - name: Lint with Flake8
      run: |
        flake8 .

    - name: Run tests with pytest
      run: |
        pytest
